# Generated by Django 3.0.4 on 2020-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='filename',
            field=models.FileField(max_length=254, upload_to=None),
        ),
    ]
