# Generated by Django 3.0.4 on 2020-03-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200311_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='filename',
            field=models.FileField(max_length=254, upload_to='Files'),
        ),
    ]
