# Generated by Django 3.0.4 on 2020-03-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20200317_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Financial_Aid_System_Applicant_ID', models.IntegerField()),
                ('Total_Tuition', models.IntegerField()),
                ('Recommended_Award', models.IntegerField()),
                ('Rec_Award_Perc_Tuition', models.FloatField()),
                ('Children_in_Applicants_HH', models.IntegerField()),
                ('Est_Household_Contribution', models.IntegerField()),
                ('Total_Income', models.IntegerField()),
                ('Total_Available_for_Tuition', models.IntegerField()),
                ('Total_Assets', models.IntegerField()),
                ('Total_Liabilities', models.IntegerField()),
                ('Total_Net_Worth', models.IntegerField()),
                ('P1_Alumni_Academy', models.IntegerField()),
                ('P1_Alumni_Camp', models.IntegerField()),
                ('P1_Alumni_Institute', models.IntegerField()),
                ('P1_Alumni_All_State', models.IntegerField()),
                ('P2_Alumni_Academy', models.IntegerField()),
                ('P2_Alumni_Camp', models.IntegerField()),
                ('P2_Alumni_All_Stat', models.IntegerField()),
                ('P2_Alumni_Institute', models.IntegerField()),
                ('Sum_Alum', models.IntegerField()),
                ('Grade', models.IntegerField()),
                ('Primary_Arts_Area', models.IntegerField()),
                ('Aid_Total_Need', models.IntegerField()),
                ('Aid_Merit', models.IntegerField()),
                ('Aid_Inst_Grant', models.IntegerField()),
                ('Sex', models.IntegerField()),
                ('Behavior_Review', models.IntegerField()),
                ('Academic_Review', models.IntegerField()),
                ('Health_Review', models.IntegerField()),
                ('Learning_Specialist_Review', models.IntegerField()),
                ('CAPS_Review', models.IntegerField()),
                ('Sum_Review', models.IntegerField()),
                ('Tuition_Default', models.IntegerField()),
                ('Art_Rating', models.IntegerField()),
                ('Accepted', models.IntegerField()),
                ('Attended_Camp', models.IntegerField()),
                ('Attended_Inst', models.IntegerField()),
                ('Attended_Sum', models.IntegerField()),
                ('Tuition_Remander', models.IntegerField()),
                ('Total_FA', models.IntegerField()),
                ('Percent_FA', models.FloatField()),
                ('Enrolled', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CsvFileData',
        ),
    ]
