# Generated by Django 3.0.4 on 2020-03-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20200317_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='Art_Rating',
            field=models.FloatField(),
        ),
    ]
