# Generated by Django 3.0.4 on 2020-03-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20200318_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='Aid_Total_Need',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Total_FA',
            field=models.FloatField(),
        ),
    ]
