# Generated by Django 3.0.4 on 2020-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20200318_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='Academic_Review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Accepted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Aid_Inst_Grant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Aid_Merit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Aid_Total_Need',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Art_Rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Attended_Camp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Attended_Inst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Attended_Sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Behavior_Review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='CAPS_Review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Children_in_Applicants_HH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Enrolled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Est_Household_Contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Financial_Aid_System_Applicant_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Health_Review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Learning_Specialist_Review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='P1_Alumni_Academy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='P1_Alumni_All_State',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='P1_Alumni_Camp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='P1_Alumni_Institute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='P2_Alumni_Academy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='P2_Alumni_All_Stat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='P2_Alumni_Camp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='P2_Alumni_Institute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Percent_FA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Primary_Arts_Area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Rec_Award_Perc_Tuition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Recommended_Award',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Sex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Sum_Alum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Sum_Review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Total_Assets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Total_Available_for_Tuition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Total_FA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Total_Income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Total_Liabilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Total_Net_Worth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Total_Tuition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Tuition_Default',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='Tuition_Remander',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
